[mgr]
ratio = [0, 1, 0]
sort_by = "natural"
show_hidden = true

[opener]
edit = [
    { run = 'herdr pane split --direction right --ratio 0.8 --current --command "nvim %s" --close-on-exit', orphan = true, desc = "Edit in split pane", for = "unix" },
]
