[mgr]
ratio = [0, 1, 0]
sort_by = "natural"
show_hidden = true

[opener]
edit = [
    { run = 'yazi-open.sh "%*"', orphan = true, desc = "Edit in nvim pane", for = "unix" },
]
imgview = [
    { run = 'chafa -f kitty "%*"; read -r', block = true, desc = "View image (chafa)", for = "unix" },
]
open = [
    { run = 'open "%*"', orphan = true, desc = "Open with system", for = "macos" },
    { run = 'xdg-open "%*"', orphan = true, desc = "Open with system", for = "linux" },
]

[open]
prepend_rules = [
    { name = "*/", use = ["edit"] },
    { mime = "image/*", use = ["imgview", "open"] },
    { name = "*.html", use = ["edit", "open"] },
    { name = "*.htm", use = ["edit", "open"] },
    { mime = "text/*", use = ["edit"] },
    { name = "*.md", use = ["edit"] },
    { name = "*.markdown", use = ["edit"] },
]
